DATALOADER: {ASPECT_RATIO_GROUPING: false, SIZE_DIVISIBILITY: 32}
DATASETS:
  GENERAL_COPY: 4
  OVERRIDE_CATEGORY: '[{"id": 1, "name": "  ", "supercategory": "pieces"}, {"id":
    2, "name": "black bishop", "supercategory": "pieces"}, {"id": 3, "name": "black
    king", "supercategory": "pieces"}, {"id": 4, "name": "black knight", "supercategory":
    "pieces"}, {"id": 5, "name": "black pawn", "supercategory": "pieces"}, {"id":
    6, "name": "black queen", "supercategory": "pieces"}, {"id": 7, "name": "black
    rook", "supercategory": "pieces"}, {"id": 8, "name": "white bishop", "supercategory":
    "pieces"}, {"id": 9, "name": "white king", "supercategory": "pieces"}, {"id":
    10, "name": "white knight", "supercategory": "pieces"}, {"id": 11, "name": "white
    pawn", "supercategory": "pieces"}, {"id": 12, "name": "white queen", "supercategory":
    "pieces"}, {"id": 13, "name": "white rook", "supercategory": "pieces"}]'
  PREDEFINED_TEXT: odinw/original/ChessPieces/category_description.json
  REGISTER:
    test: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/test/annotations_without_background.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/test}
    train: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/annotations_without_background.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_10_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot10_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_10_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot10_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_10_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot10_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_1_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot1_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_1_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot1_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_1_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot1_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_3_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot3_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_3_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot3_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_3_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot3_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_5_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot5_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_5_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot5_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    train_5_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train/fewshot_train_shot5_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/train}
    val: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/annotations_without_background.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_10_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot10_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_10_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot10_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_10_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot10_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_1_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot1_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_1_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot1_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_1_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot1_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_3_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot3_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_3_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot3_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_3_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot3_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_5_3: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot5_seed3.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_5_30: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot5_seed30.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
    val_5_300: {ann_file: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid/fewshot_val_shot5_seed300.json,
      img_dir: odinw/ChessPieces/Chess Pieces.v23-raw.coco/valid}
  TEST: ("val",)
  TRAIN: ("train",)
INPUT: {MAX_SIZE_TEST: 1333, MAX_SIZE_TRAIN: 1333, MIN_SIZE_TEST: 800, MIN_SIZE_TRAIN: 800}
MODEL:
  ATSS: {NUM_CLASSES: 14}
  DYHEAD: {NUM_CLASSES: 14}
  FCOS: {NUM_CLASSES: 14}
  ROI_BOX_HEAD: {NUM_CLASSES: 14}
SOLVER: {CHECKPOINT_PERIOD: 100, MAX_EPOCH: 12, WARMUP_ITERS: 0}
TEST: {IMS_PER_BATCH: 8}
