DATALOADER: {ASPECT_RATIO_GROUPING: false, SIZE_DIVISIBILITY: 32}
DATASETS:
  GENERAL_COPY: 8
  OVERRIDE_CATEGORY: '[{"id": 1, "name": "follow", "supercategory": "actions"}, {"id":
    2, "name": "follow_hand", "supercategory": "actions"}, {"id": 3, "name": "land",
    "supercategory": "actions"}, {"id": 4, "name": "land_hand", "supercategory": "actions"},
    {"id": 5, "name": "null", "supercategory": "actions"}, {"id": 6, "name": "object",
    "supercategory": "actions"}, {"id": 7, "name": "takeoff", "supercategory": "actions"},
    {"id": 8, "name": "takeoff-hand", "supercategory": "actions"}]'
  PREDEFINED_TEXT: odinw/pothole/category_description.json
  REGISTER:
    minival: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/annotations_without_background.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_10_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot10_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_10_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot10_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_10_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot10_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_1_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot1_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_1_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot1_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_1_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot1_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_3_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot3_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_3_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot3_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_3_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot3_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_5_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot5_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_5_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot5_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    minival_5_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val/fewshot_minival_shot5_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/mini_val}
    test: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/test/annotations_without_background.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/test}
    train: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/annotations_without_background.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_10_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot10_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_10_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot10_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_10_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot10_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_1_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot1_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_1_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot1_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_1_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot1_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_3_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot3_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_3_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot3_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_3_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot3_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_5_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot5_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_5_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot5_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    train_5_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/train/fewshot_train_shot5_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/train}
    val: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/annotations_without_background.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_10_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot10_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_10_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot10_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_10_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot10_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_1_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot1_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_1_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot1_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_1_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot1_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_3_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot3_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_3_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot3_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_3_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot3_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_5_3: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot5_seed3.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_5_30: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot5_seed30.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
    val_5_300: {ann_file: odinw/DroneControl/Drone Control.v3-raw.coco/valid/fewshot_val_shot5_seed300.json,
      img_dir: odinw/DroneControl/Drone Control.v3-raw.coco/valid}
  TEST: ("minival",)
  TRAIN: ("train",)
INPUT: {MAX_SIZE_TEST: 1333, MAX_SIZE_TRAIN: 1333, MIN_SIZE_TEST: 800, MIN_SIZE_TRAIN: 800}
MODEL:
  ATSS: {NUM_CLASSES: 9}
  DYHEAD: {NUM_CLASSES: 9}
  FCOS: {NUM_CLASSES: 9}
  ROI_BOX_HEAD: {NUM_CLASSES: 9}
SOLVER: {CHECKPOINT_PERIOD: 100, MAX_EPOCH: 12, WARMUP_ITERS: 0}
TEST: {IMS_PER_BATCH: 8}
