DATALOADER: {ASPECT_RATIO_GROUPING: false, SIZE_DIVISIBILITY: 32}
DATASETS:
  GENERAL_COPY: 4
  OVERRIDE_CATEGORY: '[{"id": 1, "name": "0", "supercategory": "Card-Types"}, {"id":
    2, "name": "1", "supercategory": "Card-Types"}, {"id": 3, "name": "2", "supercategory":
    "Card-Types"}, {"id": 4, "name": "3", "supercategory": "Card-Types"}, {"id": 5,
    "name": "4", "supercategory": "Card-Types"}, {"id": 6, "name": "5", "supercategory":
    "Card-Types"}, {"id": 7, "name": "6", "supercategory": "Card-Types"}, {"id": 8,
    "name": "7", "supercategory": "Card-Types"}, {"id": 9, "name": "8", "supercategory":
    "Card-Types"}, {"id": 10, "name": "9", "supercategory": "Card-Types"}, {"id":
    11, "name": "10", "supercategory": "Card-Types"}, {"id": 12, "name": "11", "supercategory":
    "Card-Types"}, {"id": 13, "name": "12", "supercategory": "Card-Types"}, {"id":
    14, "name": "13", "supercategory": "Card-Types"}, {"id": 15, "name": "14", "supercategory":
    "Card-Types"}]'
  PREDEFINED_TEXT: odinw/pothole/category_description.json
  REGISTER:
    minival: {ann_file: odinw/UnoCards/raw/mini_val/annotations_without_background.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_10_3: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot10_seed3.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_10_30: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot10_seed30.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_10_300: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot10_seed300.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_1_3: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot1_seed3.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_1_30: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot1_seed30.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_1_300: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot1_seed300.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_3_3: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot3_seed3.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_3_30: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot3_seed30.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_3_300: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot3_seed300.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_5_3: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot5_seed3.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_5_30: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot5_seed30.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    minival_5_300: {ann_file: odinw/UnoCards/raw/mini_val/fewshot_minival_shot5_seed300.json,
      img_dir: odinw/UnoCards/raw/mini_val}
    test: {ann_file: odinw/UnoCards/raw/test/annotations_without_background.json,
      img_dir: odinw/UnoCards/raw/test}
    train: {ann_file: odinw/UnoCards/raw/train/annotations_without_background.json,
      img_dir: odinw/UnoCards/raw/train}
    train_10_3: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot10_seed3.json,
      img_dir: odinw/UnoCards/raw/train}
    train_10_30: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot10_seed30.json,
      img_dir: odinw/UnoCards/raw/train}
    train_10_300: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot10_seed300.json,
      img_dir: odinw/UnoCards/raw/train}
    train_1_3: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot1_seed3.json,
      img_dir: odinw/UnoCards/raw/train}
    train_1_30: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot1_seed30.json,
      img_dir: odinw/UnoCards/raw/train}
    train_1_300: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot1_seed300.json,
      img_dir: odinw/UnoCards/raw/train}
    train_3_3: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot3_seed3.json,
      img_dir: odinw/UnoCards/raw/train}
    train_3_30: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot3_seed30.json,
      img_dir: odinw/UnoCards/raw/train}
    train_3_300: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot3_seed300.json,
      img_dir: odinw/UnoCards/raw/train}
    train_5_3: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot5_seed3.json,
      img_dir: odinw/UnoCards/raw/train}
    train_5_30: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot5_seed30.json,
      img_dir: odinw/UnoCards/raw/train}
    train_5_300: {ann_file: odinw/UnoCards/raw/train/fewshot_train_shot5_seed300.json,
      img_dir: odinw/UnoCards/raw/train}
    val: {ann_file: odinw/UnoCards/raw/valid/annotations_without_background.json,
      img_dir: odinw/UnoCards/raw/valid}
    val_10_3: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot10_seed3.json, img_dir: odinw/UnoCards/raw/valid}
    val_10_30: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot10_seed30.json,
      img_dir: odinw/UnoCards/raw/valid}
    val_10_300: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot10_seed300.json,
      img_dir: odinw/UnoCards/raw/valid}
    val_1_3: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot1_seed3.json, img_dir: odinw/UnoCards/raw/valid}
    val_1_30: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot1_seed30.json, img_dir: odinw/UnoCards/raw/valid}
    val_1_300: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot1_seed300.json,
      img_dir: odinw/UnoCards/raw/valid}
    val_3_3: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot3_seed3.json, img_dir: odinw/UnoCards/raw/valid}
    val_3_30: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot3_seed30.json, img_dir: odinw/UnoCards/raw/valid}
    val_3_300: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot3_seed300.json,
      img_dir: odinw/UnoCards/raw/valid}
    val_5_3: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot5_seed3.json, img_dir: odinw/UnoCards/raw/valid}
    val_5_30: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot5_seed30.json, img_dir: odinw/UnoCards/raw/valid}
    val_5_300: {ann_file: odinw/UnoCards/raw/valid/fewshot_val_shot5_seed300.json,
      img_dir: odinw/UnoCards/raw/valid}
  TEST: ("minival",)
  TRAIN: ("train",)
INPUT: {MAX_SIZE_TEST: 1333, MAX_SIZE_TRAIN: 1333, MIN_SIZE_TEST: 800, MIN_SIZE_TRAIN: 800}
MODEL:
  ATSS: {NUM_CLASSES: 16}
  DYHEAD: {NUM_CLASSES: 16}
  FCOS: {NUM_CLASSES: 16}
  ROI_BOX_HEAD: {NUM_CLASSES: 16}
SOLVER: {CHECKPOINT_PERIOD: 100, MAX_EPOCH: 12, WARMUP_ITERS: 0}
TEST: {IMS_PER_BATCH: 8}
